const users = [
  { id: 1, name: "Ali", email: "ali@test.com" },
  { id: 2, name: "Hamza", email: "hamza@test.com" },
  { id: 3, name: "Rehman", email: "rehman@test.com" },
  { id: 4, name: "Sameer", email: "sameer@test.com" },
  { id: 5, name: "Jawad", email: "jawad@test.com" },
  { id: 6, name: "Sara", email: "sara@test.com" },
  { id: 7, name: "Ahmed", email: "ahmed@test.com" },
  { id: 8, name: "Hassan", email: "hassan@test.com" },
  { id: 9, name: "Usman", email: "usman@test.com" },
  { id: 10, name: "Zain", email: "zain@test.com" },

  { id: 11, name: "Areeb", email: "areeb@test.com" },
  { id: 12, name: "Bilal", email: "bilal@test.com" },
  { id: 13, name: "Danish", email: "danish@test.com" },
  { id: 14, name: "Fahad", email: "fahad@test.com" },
  { id: 15, name: "Kashif", email: "kashif@test.com" },
  { id: 16, name: "Imran", email: "imran@test.com" },
  { id: 17, name: "Noman", email: "noman@test.com" },
  { id: 18, name: "Shan", email: "shan@test.com" },
  { id: 19, name: "Qasim", email: "qasim@test.com" },
  { id: 20, name: "Saad", email: "saad@test.com" },

  { id: 21, name: "Ahsan", email: "ahsan@test.com" },
  { id: 22, name: "Farhan", email: "farhan@test.com" },
  { id: 23, name: "Tariq", email: "tariq@test.com" },
  { id: 24, name: "Irfan", email: "irfan@test.com" },
  { id: 25, name: "Kamran", email: "kamran@test.com" },
  { id: 26, name: "Yasir", email: "yasir@test.com" },
  { id: 27, name: "Shahzaib", email: "shahzaib@test.com" },
  { id: 28, name: "Owais", email: "owais@test.com" },
  { id: 29, name: "Rizwan", email: "rizwan@test.com" },
  { id: 30, name: "Asad", email: "asad@test.com" },

  { id: 31, name: "Zubair", email: "zubair@test.com" },
  { id: 32, name: "Waqas", email: "waqas@test.com" },
  { id: 33, name: "Umar", email: "umar@test.com" },
  { id: 34, name: "Adnan", email: "adnan@test.com" },
  { id: 35, name: "Sajid", email: "sajid@test.com" },
  { id: 36, name: "Arslan", email: "arslan@test.com" },
  { id: 37, name: "Haris", email: "haris@test.com" },
  { id: 38, name: "Talha", email: "talha@test.com" },
  { id: 39, name: "Nouman", email: "nouman@test.com" },
  { id: 40, name: "Zeeshan", email: "zeeshan@test.com" },

  { id: 41, name: "Rauf", email: "rauf@test.com" },
  { id: 42, name: "Furqan", email: "furqan@test.com" },
  { id: 43, name: "Salman", email: "salman@test.com" },
  { id: 44, name: "Mubashir", email: "mubashir@test.com" },
  { id: 45, name: "Sheryar", email: "sheryar@test.com" },
  { id: 46, name: "Junaid", email: "junaid@test.com" },
  { id: 47, name: "Azhar", email: "azhar@test.com" },
  { id: 48, name: "Khurram", email: "khurram@test.com" },
  { id: 49, name: "Faizan", email: "faizan@test.com" },
  { id: 50, name: "Mustafa", email: "mustafa@test.com" }
];

export default users;
